//user input-data types generated by cli

import { $TSObject } from "amplify-cli-core";

export function enumToHelp( obj : object ){
    return `One of ${Object.values(obj)}`;
}

export enum S3AccessType  {
    AUTH_AND_GUEST =  "authAndGuest",
    AUTH_ONLY =  "auth"
}

export enum S3PermissionType {
    CREATE = "CREATE",
    READ = "READ",
    DELETE = "DELETE",
    LIST = "LIST"
}

export type GroupAccessType = Record<string,S3PermissionType[]>;


//User input data for S3 service
export interface S3UserInputs {
     resourceName : string|undefined,
     bucketName : string|undefined,
     policyUUID : string|undefined,
     selectedGuestPermissions: S3PermissionType[],
     selectedAuthenticatedPermissions : S3PermissionType[],
     triggerFunctionName: string|undefined,
     groupPolicyMap : GroupAccessType|undefined, //{ "admingroup": [create, read,  delete, list], "secondgroup" :[...''...] }
     groupList : Array<string>|undefined   //Keys of group policy Map
}

export function defaultS3UserInputs() :S3UserInputs {
    const defaultS3UserInputValues: S3UserInputs = {
        resourceName : undefined,
        bucketName: undefined,
        policyUUID : undefined,
        selectedGuestPermissions : [],
        selectedAuthenticatedPermissions : [S3PermissionType.CREATE, S3PermissionType.READ, S3PermissionType.LIST],
        triggerFunctionName:undefined,
        groupPolicyMap: undefined,
        groupList: undefined
    };
    return defaultS3UserInputValues;
}